services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/database
      - SECRETKEY=${SECRETKEY}
      - SESSION_AUTH_NAME=${SESSION_AUTH_NAME}
    volumes:
      - ./src:/src
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
