version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRETKEY=${SECRETKEY}
      - SESSION_AUTH_NAME=${SESSION_AUTH_NAME}