services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/database
      - SECRETKEY=${SECRETKEY}
      - SESSION_AUTH_NAME=${SESSION_AUTH_NAME}
    volumes:
      - ./src:/src
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"